MeltanoLabs/tap-github

poetry.lock
pyproject.toml

This PR declares support for python 3.9, and updates poetry.lock to match those changes.

Add python3.9 support

---

.github/workflows/test_tap.yml
poetry.lock
pyproject.toml
tap_github/client.py

This PR sets up a simple CI workflow that:
- installs dependencies with poetry
- runs black and mypy
- runs pytest tests
- does all the above in all supported python versions
This PR should be merged only after https://gitlab.com/meltano/sdk/-/merge_requests/150 has been merged (mypy won't succeed without it, but I've verified locally that it does work if the `py.typed` file is manually added to the dependency)
Once we have a decent CI setup here, it would be useful to copy the workflow file into the SDK's template, so that any new tap can use the same logic.

Setup ci on github actions

---

tap_github/streams.py

This PR does a couple of things:
- update the `issues` stream schema to match the docs (and actual API output) a bit more closely. I've not included *all* fields, namely excluding the "obvious" ones that can be computed trivially by appending a common postfix to the base url.
- modify the `issue_comments` stream to be a child of `repositories` as discussed in #8 and update the schema like above
Depending on how quickly this gets merged, I might add `issue_events` here, or in a separate PR, following the same logic.

Add issues and issue_comments streams

---

tap_github/streams.py

I let some errors slip through in #9 sorry. These definitions actually seem to work when running the tap against the API (I'll blame it on hasty copy/pasting :sweat_smile: )

Fix some errors in stream schema definitions

---

.gitignore
tap_github/streams.py
tap_github/tap.py

This PR adds a README stream to the tap.
Tested on our own DB and seems to be outputting the correct schema :+1:
Concerns:
- Is the `url` a decent primary key here?
- We could consider splitting our our streams to more than one file as things continue to grow

Add README stream

---

tap_github/streams.py
tap_github/tap.py

This PR adds another stream to the tap, for commits.
I improvised a bit for the replication key, as the API does not provide a top-level timestamp field, and couldn't figure out a way to use a nested one.
There is no testing either, but I've run the tap against `target-postgres` and the data appears as expected, which is better than nothing :)

Add commits stream

---

.gitignore
tap_github/client.py
tap_github/streams.py
tap_github/tap.py

Adding a stream for CommunityProfile.
Enhancing error handling because fetching `community/profile` from the GitHub API sometimes return a `404 - Not Found`. See #16 for more details.

Add CommunityProfile stream and enhance error handling

---

tap_github/streams.py
tap_github/tap.py

Following up on #17, I would like to propose this solution.
This PR:
- creates a new PullRequests stream that fetches PRs only (regardless of state).
- updates the Issue stream to fetch all issues (and PRs) regardless of state and add a "type" field

Add PullRequests stream and get all issues and prs regardless of state

---

tap_github/streams.py
tap_github/tests/fixtures.py
tap_github/tests/test_tap.py

Quick fix for reactions mapping. As a side question, now that we use the GitHub token, what do you think of adding more projects to tests @aaronsteers? We could propose https://github.com/mapswipe/mapswipe which @laurentS and I work on and has varied inputs.

Fix reactions mapping type in Issues and PRs streams

---

tap_github/streams.py

Fixes https://github.com/MeltanoLabs/tap-github/issues/40

Tolerate missing readme file for a repo

---

tap_github/streams.py

Fixes #44 
I've run the stream on just over 200k issues to test and have not seen any problems so far (including the one that was causing the problem in the first place).
The check for an empty body puzzles me a bit, but the tap failed almost immediately without it.

Clean control chars from issue body field

---

tap_github/client.py

Trivial PR to correct a typo in the code.
A quick review of github API docs (eg [here](https://docs.github.com/en/rest/reference/repos#list-organization-repositories)) says that the max is 100, not 1k.

Adjust max-per-page constant to match api docs

---

.github/workflows/test_tap.yml
poetry.lock
pyproject.toml

This PR drops support for python 3.6 both in `pyproject.toml` and CI. Fixes #57 
Notes:
- I have not added python 3.10 in CI yet, as it's likely to just make things worse with rate limits
- I had to pin `singer-sdk` to `0.3.13` as `0.3.14` has a breaking change with our use of `tolerated_http_errors`. We will have to change the logic in the tap before we can upgrade to the latest sdk. Issue tracked in #58
- this in turn means I couldn't upgrade `pyproject.toml` to support python 3.10 as poetry then fails on dependency resolution, because that version of sdk hasn't declared support for 3.10 yet.

Drop support for python 3.6

---

.github/workflows/test_tap.yml
.gitignore
poetry.lock
pyproject.toml
tap_github/tests/__init__.py

Relates to #43 and #14
This PR sets up a simple caching mechanism for github api requests made by the tap during testing.
:warning: I had to make this PR on top of #59 because dependency resolution wouldn't complete otherwise.
The implementation is pretty much as suggested by @aaronsteers in #43:
- the matrix is setup to run jobs sequentially (specifically, not more than 1 job in parallel :wink: ) With caching, on my machine, `pytest` runs in 7 sec instead of 125s, so doing jobs in sequence does not really matter.
- the api responses are saved in a sqlite db file, which github should cache after a job completes successfully.
- github keeps cached files for up to 7 days (more if they keep being accessed), but we expire the content of a response after 24h.
- API keys should be excluded from …

Cache api requests in tests

---

.github/workflows/test_tap.yml

The quotes are needed to prevent github from reading it as `3.1`.

Support python 3.10 in CI

---

tap_github/streams.py

This is a temporary patch for #52 but does not fix the core issue in a satisfactory manner.
This allows the tap to keep running, which is a better outcome than a plain crash :man_shrugging:

Tolerate 502 errors from github on issue comments

---

poetry.lock
pyproject.toml
tap_github/authenticator.py
tap_github/client.py
tap_github/repository_streams.py
tap_github/tap.py

Add the repo `/stats/contributors` endpoint to fetch weekly contribution data

Add StatsContributorsStream

---

tap_github/repository_streams.py

Following on @laurentS option to fix #64 by using a literal version of reaction emojis +1/-1 to plus_one/minus_one

Use literal reaction names [breaking]

---

tap_github/client.py

Returning the full path of the failed queries on errors instead of the ominous generic path `404 Client Error: Not Found for path: /repos/{org}/{repo}` -> `404 Client Error: Not Found for path: /repos/haha/idonotexist`

Get actual path on errors

---

tap_github/repository_streams.py

We've had a database review for performance bottlenecks by a postgresql expert, and one of the recommendations was to swap the order of index columns in the indexes created on the tables that come out of this tap + `target-postgres`.
The commit in this PR shows how the columns were reordered, allowing for faster updates. The gist of it is that the columns with highest cardinality (most distinct values) should come first, followed by lower cardinality.
This change seems to have helped on our setup.
2 caveats:
- the exact order might vary somewhat depending on what data is being fetched. The order below seems to work for us at this point, but should work in most cases (it seems fairly obvious that there are more users than orgs for instance).
- This might be pretty specific to the way the …

Change order of columns in pkey indexes to improve db performance

---

tap_github/client.py
tap_github/repository_streams.py

Tweaking our warning for replication_key handling since "commit_timestamp" and "created_at" work by default.
And leveraging our custom "since" logic to exit early with the "created_at" replication_key

Silence unnecessary replication_key warnings

---

tap_github/client.py
tap_github/repository_streams.py
tap_github/user_streams.py

As crazy as it sounds, GitHub doesn't have the `since` param on a lot of endpoints.... such as /starred, /stargazers, /events and /pulls, which do not support the "since" parameter out of the box. So we use a workaround here to exit early.

Mitigate GitHub API not having "since" parameter for /pulls

---

tap_github/client.py

This PR should fix the CI failures we have seen such as https://github.com/MeltanoLabs/tap-github/actions/runs/1898146133
The failures are caused by `requests-cache` which serializes `since` with a `+00:00` timezone format instead of `Z`, and when parsed by `parse_qs`, the `+` is turned into a space.
`parse` then sees a naive timestamp, and tests fail. This only happens in CI, but the fix below has no impact elsewhere as there are no spaces in the string.

Fix broken timestamp in ci with requests-cache

---

tap_github/repository_streams.py
tap_github/tap.py

This PR tries to address https://gitlab.com/meltano/sdk/-/issues/217 within `tap-github` using a specific solution.
It might be possible to generalise the idea and add something equivalent in the sdk.
This has become fairly high priority for us:
- we sync different streams independently (1 by 1) at different frequencies (some hourly, some daily, some less often). Currently all child streams force a call to the `/repo` endpoint.
- github API quota usage is essentially doubled in incremental mode. eg: syncing `issues` for 1 repo yields 2 API calls, 1 to repos, 1 to issues, and the result of the first call is discarded, which seems wasteful.
- we have seen an increase in random 401 errors from the API (despite valid auth, and remaining within rate limits), these lead to the tap crashing with …

Add config option to skip API calls to repositories

---

tap_github/client.py

Unfortunately, the GitHub API returns 401 unauthorized errors from time to time. Randomly...
To mitigate that, one option is to make 401 a retriable error for now.

Retry on 401 unauthorized errors

---

pyproject.toml

This fixes the version definition to allow using python 3.10.2+ (current stable python is 3.10.3).

Support latest minor python 3.10.x versions

---

tap_github/client.py

This PR corrects how the tap handles HTTP 401 error codes from the API:
the `Unauthorized` string appears in `response.reason` not `response.content`.
It also adds a fatal error if the token in invalid as there is no point retrying in that case.

Correct error handling for http 401 codes

---

tap_github/repository_streams.py

This PR adds `repo, org` to commit records to help downstream processing, for instance to filter by repo.
Right now it's actually difficult to do so, as it would require filtering records whose url contains the repo name, or something along those lines.

Add repo context to commits stream

---

tap_github/repository_streams.py
tap_github/tap.py

New streams for GitHub Actions :
- [`workflows`](https://docs.github.com/en/rest/reference/actions#list-repository-workflows): All workflows  in a repository.
- [`workflow_runs`](https://docs.github.com/en/rest/reference/actions#list-workflow-runs-for-a-repository): All workflow runs  in a repository.
- [`workflow_run_jobs`](https://docs.github.com/en/rest/reference/actions#list-jobs-for-a-workflow-run): All jobs executed in a workflow run. For example, every value in a matrix corresponds to a job.

Workflow streams

---

tap_github/client.py
tap_github/repository_streams.py
tap_github/user_streams.py

After merging #80, I noticed a ?weird? behavior with replication keys that I think stems from the ignore_parent_replication_key and `_set_compatible_replication_methods` [sdk](https://gitlab.com/meltano/sdk/-/blob/main/singer_sdk/tap_base.py#L330)
This PR is an attempt to fix a warning that pops up but doesn't feel normal:
`Beginning incremental sync of 'pull_requests' with context: {'org': 'ourresearch', 'repo': 'oadoi'}...`
`The replication key 'None' is not fully supported by this client yet.` which happens to almost all our streams.
@aaronsteers you're probably the most versed in replication_keys, so very curious to get your thoughts.

Add parent replication_key

---

tap_github/client.py

With the current logging implementation, we end up printing the word "error" for tolerated status codes.
Eg. `502 Tolerated Status Code: b'{\n  "message": "Server Error"\n}\n' (Reason: Bad Gateway) for path: /repos/kubevirt/kubevirt/issues/comments`
Instead, I propose to remove the content print and simplify the message to:
`502 Tolerated Status Code (Reason: Bad Gateway) for path: /repos/kubevirt/kubevirt/issues/comments`

Avoid printing out "error" in tolerated status code message

---

README.md

Adds guidance on how to pin to a specific release version.

Release pinning guidance

---

pytest.ini
tap_github/client.py
tap_github/repository_streams.py
tap_github/tests/__init__.py
tap_github/tests/test_tap.py
tap_github/user_streams.py

This PR aims to resolve a number of issues by adding the numeric repo id to the context of all streams in the tap.
We have been having issues with repos changing names, incorrect case in the config file, etc... leading to problems with joins downstream. We are using `org/repo` to connect the various streams together, but since those values are not stable (for instance if a repo is renamed), this can lead to issues.
To remedy this, we fetch the github `id` (or `databaseId` in their graphql API lingo) and add it to all streams via the child context. This `id` is stable across renames, which should help match records over time.
The PR adds a "preflight" request to the graphql API which fetches said `id` for all the repos in the config file (if `repositories` is indeed in the config). At the …

Fetch databaseId for repos and users when initializing streams

---

README.md
pyproject.toml
tap_github/authenticator.py

Adding an environment variable GITHUB_APP_PRIVATE_KEY to enable authentication as a GitHub app which have higher API limits.
https://docs.github.com/en/enterprise-server@3.3/developers/apps/building-github-apps/rate-limits-for-github-apps#server-to-server-requests
GitHub Apps making server-to-server requests use the installation's minimum rate limit of 5,000 requests per hour. If an application is installed on an organization with more than 20 users, the application receives another 50 requests per hour for each user. Installations that have more than 20 repositories receive another 50 requests per hour for each repository. The maximum rate limit for an installation is 12,500 requests per hour.

Enable GitHub App authentication with private key

---

tap_github/repository_streams.py
tap_github/user_streams.py

The users stream is giving unexpected results for organizations as the graphql endpoint is very picky about the user type and won't give any info for orgs.
This PR uses a different `repositoryOwner` query to cover both user and organization user types while enriching the config provided usernames.
It is a bit hacky because the API does not include the `databaseId` for this query, so we parse it from a url :/

Fix user verification query and accept organization logins

---

poetry.lock
pyproject.toml
tap_github/authenticator.py
tap_github/client.py
tap_github/tap.py
tap_github/user_streams.py

Add deep pagination for Graphql streams. Fixes #89 
This also fixes #106 
This requires setting up extra pagination parameters in the query like this:
```
query userContributedTo($username: String! $nextPageCursor_1: String) {
user (login: $username) {
repositoriesContributedTo (first: 100 after: $nextPageCursor_1 includeUserRepositories: true orderBy: {field: STARGAZERS, direction: DESC}) {
pageInfo {
hasNextPage_1: hasNextPage
startCursor_1: startCursor
endCursor_1: endCursor
}
nodes {
node_id: id
name_with_owner: nameWithOwner
open_graph_image_url: openGraphImageUrl
stargazer_count: stargazerCount
owner {
node_id: id
login
}
}
}
}
}
```

Add pagination for GraphQl streams

---

.secrets/.gitignore
tap_github/repository_streams.py

> *What*
> 
> Dependencies url is cast as integer instead of string → Causes tap to fail
---
_from `tiguidou` with :heart:_

Cast DenpendenciesStream.url as String

---

.github/workflows/test_tap.yml
tap_github/client.py

When heavily using the GitHub API, users can encounter "secondary rate limits". This happens in particular when multiple streams are running simultaneously and make a concurrent call.
Amongst the solutions:
- wait for a bit
- change IP (out of scope for the tap)
This PR implements a 61 seconds wait and retry signal

Wait and retry on secondary limits

---

.github/workflows/test_tap.yml
poetry.lock
pyproject.toml
tap_github/tests/fixtures.py

This PR upgrades dependencies:
- `meltano/sdk` to 0.12.0
- developer tools (mypy, black, ...)
- ci workflow actions
- poetry
There's a small fix on the test fixtures loglevel config which started throwing an error.

Upgrade dependencies

---

pyproject.toml

This improves package metadata for PyPI to help with discoverability, etc...
Keys copied from the sdk `pyproject.toml` :)

Improve package metadata

---

.github/workflows/test_tap.yml
.gitignore
tap_github/tests/__init__.py

This might fix a bug in the action, from https://github.com/marketplace/actions/cache#v3:
> Fixed cache not working with github workspace directory or current directory.
Which might explain why the venv is cached, but not the api requests file?

Update CI caching action

---

tap_github/client.py
tap_github/repository_streams.py

Fixes #165 by iterating through pagination cursors with the same index if the first ones are null, and making sure that we properly reset pagination cursor for higher indices

Fix graphql pagination

---

poetry.lock
pyproject.toml
tap_github/tests/test_tap.py

This PR updates the sdk to fix a bug in state messaging from the tap which prevented certain streams (such `issue_comments`) from ending with a valid state message, making it impossible to actually run them incrementally.

Fix broken state messaging in sdk

---

tap_github/repository_streams.py

Reported in slack:
https://meltano.slack.com/archives/CMN8HELB0/p1673621544959589?thread_ts=1673611200.162959&cid=CMN8HELB0

fix: use `datetime` type for fetched_at

---

tap_github/scraping.py

This PR fixes a small bug in the `ExtraMetrics` stream which was using a *local* timestamp, instead of UTC ones used everywhere.
Running the tap in the `UTC+1` where I'm at right now led to a broken record like this (formatting added for readability):
```python
{'type': 'RECORD',
'stream': 'extra-metrics',
'record': {'open_issues': 101,
'open_prs': 15,
'dependents': 0,
'contributors': 20,
'fetched_at': '2023-02-09T12:37:27.508297+00:00',
'repo': 'mapswipe',
'org': 'mapswipe',
'repo_id': 68943183},
'time_extracted': '2023-02-09T11:37:27.508573+00:00',
'__raw_line_size': 295})])
```
Note how the timestamps differ by 1h, with `fetched_at` appearing to be in the future at the time of processing this record.
The PR makes these timestamps equal.

fix: Use an aware timestamp in UTC timezone

---

tap_github/client.py

This PR fixes a small bug in the cost calculation logic which caused the tap to crash in some cases for lack of the expected key in the server's response.
As the sdk calculates costs before iterating through records, where the main error handling logic lives, it would sometimes never reach that logic. This change prevents this and makes sure that the main error logic is reached, at the expense of "proper" cost calculation.

fix: Prevent crash during cost calculation

---

tap_github/client.py
tap_github/repository_streams.py
tap_github/tests/test_tap.py

The tap (and the sdk) were not reporting any graphql errors (because annoyingly, graphql chooses to ignore good HTTP practice by returning a status 200 even on fatal errors).
This PR adds a minimal level of reporting by checking for `errors` in the response.
@edgarrmondragon The sdk does not seem to check for graphql errors at all, it simply defers to the REST streams `validate_response` which is not adapted to it. Is it worth adding something in the `sdk` in that respect?

fix: Raise an api error on graphql errors

---

tap_github/repository_streams.py

Fix #182 by seting MAX_RESULTS_LIMIT for Releases stream.

fix: Set MAX_RESULTS_LIMIT for Releases stream

---

tap_github/repository_streams.py

When there are no stargazers in the next page function, it fails, this PR addresses it, fixing https://github.com/MeltanoLabs/tap-github/issues/191

fix: Handle empty stargazers

---

tap_github/scraping.py
tap_github/tests/test_tap.py

Partially addresses #205 by avoiding a crash on high values.
The downside is that we don't get the real value from the HTML content as github does not provide it.
See the linked ticket for more details.

fix: update html parser to work on very high values like 5k+

---

.github/workflows/test_tap.yml

Fixes (hopefully) #119.
See details in the issue. Hopefully this PR's tests should already see the benefit of the cache.

fix: update ci caching logic

---

tap_github/organization_streams.py

fix: If a member is part of multiple teams, they will only be listed once

---

poetry.lock
tap_github/repository_streams.py
tap_github/tests/test_tap.py

A quick and dirty PR to get around the `torvalds/linux` problem (and other similar repos) where the contributors list is so large that github gives up with a confusing error code.
To be updated once https://github.com/meltano/sdk/pull/1754 is merged/released.

fix: skip repos for which contributors list is too large

---

tap_github/client.py

Github's API sometimes returns an empty response `b''` which is not standards compliant (it's undocumented, and also not clear when/why this happens).
This triggers an exception in `urllib` and `requests` (both packages have clarified they do not intend to handle this case, it's a server-side problem):
```
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```
which bubbles up to the tap and its backoff handler. This patch just prevents the handler from crashing in such a case. It does not try to address further consequences.

fix: check that exc.response is not empty before accessing it

---

tap_github/repository_streams.py

Handle the case when a repo is renamed by logging the info.

feat: log when a repo is renamed

---

tap_github/repository_streams.py

Just like some issue bodies contain control char `\x00` which crashes targets like postgresql, it appears that some issue titles can cause the same problem, eg. https://github.com/cockroachdb/cockroach/issues/100343 or https://github.com/cockroachdb/cockroach/issues/100344.
This PR applies the same logic to fix the problem.

fix: clean up control chars from issue titles as well

---

tap_github/repository_streams.py

This PR applies the same logic to PRs as was done for issues in #232

fix: prevent crash on null chars in pr titles

---

pyproject.toml

The version in pyproject.toml was out of sync with the latest release. 
I guess the bumping of this version should be part of #47.

chore: Update version in pyproject.toml

---

tap_github/repository_streams.py

This PR introduces a minor updates to the RepositoryStream class such the `MAX_RESULTS_LIMIT` is applied only when the path is :
`/search/repositories/`,
and not when it's 
`/repos/{org}/{repo}`
or 
`/orgs/{org}/repos`.
These last two endpoints can handle results greater than 1000.

feat: Sets MAX_RESULTS_LIMIT to 1000 when RepositoryStream.path is /search/repositories only

---

tap_github/repository_streams.py

I have updated the `replication_key` for GitHub releases to `created_at` field vs the `published_at` field. 
The `pubished_at` field can be `null` according to the [REST API endpoints for releases](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28)
This was causing the below error
```
{"TypeError: '>' not supported between instances of 'NoneType' and 'str'"}
```
`created_at` field can't be null so this should fix that.

fix: releases replication key

---

tap_github/repository_streams.py

This pull request adds the `created_at` property to the `workflow_run_jobs` schema. This allows users to extract the creation time of workflow run jobs and would be helpful in the tracking individual jobs `queue_time`.
- Updated `repository_streams.py` to include `created_at` in the `schema` definition of the `workflow_run_jobs` stream.
1. Confirmed that Github REST API endpoint for workflow jobs response returns `created_at` field in the response.
2. Tested the changes locally using Meltano to ensure the `created_at` field is correctly included and populated.

feat: Add `created_at` to `workflow_run_jobs` schema

---

tap_github/repository_streams.py

The collaborators stream pulls one row per selected repo per user who is a known collaborator of that repo, so `id` (the user ID) alone isn't sufficient to describe the grain.  This PR adds `repo` and `org` to the primary keys to capture the fact that there can be a row for each user x repo pair.
My motivation is that I'm getting an error `Query error: UPDATE/MERGE must match at most one source row for each target row ...` when trying to extract this stream sequentially with `target-bigquery` and the [upsert](https://hub.meltano.com/loaders/target-bigquery/#upsert-setting) setting turned on, and that sounds related to the fact that the column set as the primary key isn't distinctive.

fix: Expand CollaboratorsStream primary keys

---

tap_github/authenticator.py
tap_github/tests/test_authenticator.py

**Note: In this PR I am not changing functionality but just refactoring to make functionality changes possible in a future PR.** Essentially: [make the change easy, then make the easy change.](https://x.com/KentBeck/status/250733358307500032?lang=en)
My goal is to add github app token features, for example refreshing app tokens before they expire (they're only good for an hour and currently don't refresh), and allowing multiple app tokens
Currently, personal and app tokens are stored in the same list and treated interchangeably, so some structural changes are needed in order to handle them differently.  My plan is to develop PersonalTokenManager and AppTokenManager classes so the code for working with each token type can be built into its manager class.  In this PR I start by proposing to …

refactor: Authenticator refactoring (preparation for app token refreshing)

---

tap_github/repository_streams.py

**Summary**
This pull request adds the `run_attempt` property to the workflow_runs schema. This will give the ability to filter out re-runs(`run_attempt>1`) in the workflow runs metrics.
**Changes**
Updated `repository_streams.py` to include `run_attempt` in the schema definition of the workflow_runs stream.
**Testing**
1. Confirmed that Github REST API endpoint for workflow runs response returns `run_attempt` field in the response.
2. Tested the changes locally using Meltano to ensure the `run_attempt` field is correctly included in response and populated in the target.

feat: Add `run_attempt` to `workflow_runs` schema

---

tap_github/authenticator.py
tap_github/tests/test_authenticator.py

This PR continues the work started in https://github.com/MeltanoLabs/tap-github/pull/281, completing the major refactor. This is accomplished by creating PersonalTokenManager and AppTokenManager classes, moving logic to them, and adding tests.
After this PR, I'll be able to easily implement refreshing for app tokens and other app token related features.
In additional to the added unit tests, I have tested running an extractor on top of the proposed code, in a couple scenarios:
with auth_token? | with additional_auth_tokens? | with personal tokens in env? | with app token? | # tokens that should be used | # tokens used in test run
--|--|--|--|--|--
no | no | no | yes | 1 | 1 ✅ 
yes | yes (1) | no | yes | 3 | 3 ✅ 
no | yes (2) | no | yes | 3 | 3 ✅ 
I am not easily able to test the case of …

fix: Tokens in config are no longer ignored when there are tokens in the environment, part of refactoring in preparation for app token refreshing

---

tap_github/authenticator.py
tap_github/tests/test_authenticator.py

Addresses the problem described by @camerondavison [here](https://github.com/MeltanoLabs/tap-github/pull/284#discussion_r1717520222), and introduced in https://github.com/MeltanoLabs/tap-github/pull/284.
If not provided, installation ID should be set to None, since that is the way `generate_app_access_token` expects a missing installation ID to be represented.

fix: fix problem when app token used without installation ID provided

---

tap_github/repository_streams.py

Related:
- Closes https://github.com/MeltanoLabs/tap-github/issues/216

fix: Remove misleading replication key from `workflows` and `workflow_runs` stream

---

poetry.lock
pyproject.toml

- Closes https://github.com/MeltanoLabs/tap-github/issues/349
- https://github.com/meltano/sdk/pull/2525
- https://github.com/meltano/sdk/releases/tag/v0.39.0

fix: Make `cryptography` an explicit dependency

---

tap_github/repository_streams.py

This PR also contains some forward fixes following https://github.com/MeltanoLabs/tap-github/pull/345, namely
- a mis-indented `return` statement was causing all PR diff records to be 'skipped'
- added `404` to list of known Github API errors
For completeness purposes, 2 new PR diff properties have been added: `success` and `error_message`.
- If a PR diff is successfully fetched, `success`=`True` and `error_message` is null.
- If a PR diff is 'skipped' for any reason (e.g., GIthub API error, diff size is too large) a record will still be made for it with `success`=`False` and the respective `error_message` (so users can at least know which PRs have diffs that weren't retrieved).
I've tested my changes on my end and it all seems to be working successfully (records being produced with the …

feat: include records for failed PR diff fetches in `PullRequestDiffsStream`

---

tap_github/repository_streams.py

Fixing a bug in the new BranchesStream and TagsStream that was brought in this last [PR](https://github.com/MeltanoLabs/tap-github/pull/357). By not having the `name` in the primary keys it returns one data entry per org/repo. This should allow the stream to pick up all tags and branches in a given repo now. (tested this downstream and it works as expected)

feat: Updated primary key to include name in `branches` and `tags` streams

---

tap_github/organization_streams.py
tap_github/streams.py

Adds into the Organzation Stream a way to also get organization members. There is currently a team members, but not all members for the org are captured by that.

feat: Add support for organization members

---

tap_github/repository_streams.py

We ran into an `AttributeError: 'NoneType' object has no attribute 'pop'` error while testing the IssueEventsStream, it's originating from [this line](https://github.com/MeltanoLabs/tap-github/blob/9033fe4d2b28386c6e8c6fb02262d80b862cd05d/tap_github/repository_streams.py#L1032).
It appears to be possible for row to have an `issue` key but for its value in the dict to be None.  This PR adds a check for it.
We've tested the fix on our end successfully.

fix: check for null row["issue"] in issue events stream

---

tap_github/repository_streams.py

The various context items being shared from the parent Pull Request Stream to the Review stream were not being persisted to the data layer. This fixes that

fix: Pull Request Reviews not saving parent stream context ids

---

.github/workflows/project_add.yml
.github/workflows/release.yml
.github/workflows/test_tap.yml

This will help prevent attacks such as [this one](https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/).
Dependabot is able to update these versions automatically, and it will preserve the readable version comments.

chore: pin GitHub Actions versions to commit hashes

---

tap_github/client.py
tap_github/repository_streams.py

Small followup to https://github.com/MeltanoLabs/tap-github/pull/372. 
Realized that the `tolerated_http_errors` should be the same for all `GithubDiffsStream` class members, not only `PullRequestDiffs`. I have verified that changes work as expected 👍🏻 
Thank you in advance!

fix: Move tolerated errors to parent `GitHubDiffStream` class

---

tap_github/client.py

- Closes https://github.com/MeltanoLabs/tap-github/issues/391
- https://github.com/meltano/sdk/pull/2965
- https://github.com/meltano/sdk/pull/2978

fix: Avoid accessing `._http_headers` attribute

---

tap_github/repository_streams.py

hi, adding some acceptable errors:
1. some repos require `admin:org` and i don't want to give `admin:write` scope. 
2. some repos don't have those paths

fix: add silent fails for collaborators + contributors

---

tap_github/client.py
tap_github/repository_streams.py

We've begun getting this error for one of our orgs:
> Pagination with the page parameter is not supported for large datasets, please use cursor based pagination (after/before)
I suspect Github has added a new restriction here as we haven't see this issue in the past even with large scale extractions, and it's happening now with a relatively small one.
This PR adds a class variable `use_cursor_pagination` in `GitHubRestStream` that can be toggled to have a given stream subclass use cursor-based pagination instead.  I'm leaving it False by default and only setting it to True in `IssuesStream` because I don't know if other endpoints support it.  If it turns out to be needed in other streams in the future, it should be easy to set.
I've successfully tested this change in my environment.

fix: Implement cursor-based pagination and use it for IssuesStream

---

tap_github/organization_streams.py
tap_github/streams.py
tap_github/tap.py

Add 3 streams to pull corresponding Github ProjectV2 data:
- ProjectsStream for [ProjectV2](https://docs.github.com/en/graphql/reference/objects#projectv2) objects
- ProjectFieldConfigurationsStream for [ProjectFieldConfiguration](https://docs.github.com/en/graphql/reference/objects#projectv2fieldconfiguration) objects
- ProjectItemFieldValuesStream for [ProjectItemFieldValue](https://docs.github.com/en/graphql/reference/unions#projectv2itemfieldvalue) objects
Question to Meltano team: what fields should be included in the stream and what should be excluded? Current implementation tries to include as many fields as possible available from Graphql.

feat(taps): Add streams for projectv2, project v2 field configurations and project v2 item field values
